python evaluate.py --coco-ann-path without_class_maskdino/annotations/fold1/test_annotation_coco_polygon.json --pred-path without_class_maskdino/predictions/cvs-challenge_pretrained_endoscapes_fold1_2/inference/coco_instances_results.json --output_path ./metrics_outputs/MaskDino/Without_categories/fold1 --tasks instruments --metrics segmentation --filter --selection topk_thresh --selection_info 5,0.1
python evaluate.py --coco-ann-path without_class_maskdino/annotations/fold2/test_annotation_coco_polygon.json --pred-path without_class_maskdino/predictions/cvs-challenge_pretrained_endoscapes_fold2_2/inference/coco_instances_results.json --output_path ./metrics_outputs/MaskDino/Without_categories/fold2 --tasks instruments --metrics segmentation --filter --selection topk_thresh --selection_info 5,0.1

python evaluate.py --coco-ann-path /media/SSD1/scanar/endovis/LEMIS-challenge/region_proposals/data/sages/annotations/fold1/test_annotation_coco_polygon.json --pred-path /home/jclyons/endovis/challenge_2025/MaskDINO/outputs/cvs-challenge_pretrained_endoscapes_fold1_2/inference/coco_instances_results.json --output_path ./metrics_outputs/MaskDino/With_categories/fold1 --tasks instruments --metrics segmentation --filter --selection topk_thresh --selection_info 5,0.1
python evaluate.py --coco-ann-path /media/SSD1/scanar/endovis/LEMIS-challenge/region_proposals/data/sages/annotations/fold2/test_annotation_coco_polygon.json --pred-path /home/jclyons/endovis/challenge_2025/MaskDINO/outputs/cvs-challenge_pretrained_endoscapes_fold2_2/inference/coco_instances_results.json --output_path ./metrics_outputs/MaskDino/With_categories/fold2 --tasks instruments --metrics segmentation --filter --selection topk_thresh --selection_info 5,0.1

# Mask2former TODO
python evaluate.py --coco-ann-path without_class_mask2former/annotations/fold1/test_annotation_coco_polygon.json --pred-path without_class_mask2former/predictions/CVS_SwinL_cutted_from_end2023_cutted_fold1/inference/coco_instances_results.json --output_path ./metrics_outputs/Mask2Former/Without_categories/fold1 --tasks instruments --metrics segmentation --filter --selection topk_thresh --selection_info 5,0.1
python evaluate.py --coco-ann-path without_class_mask2former/annotations/fold2/test_annotation_coco_polygon.json --pred-path without_class_mask2former/predictions/CVS_SwinL_cutted_from_end2023_cutted_fold2/inference/coco_instances_results.json --output_path ./metrics_outputs/Mask2Former/Without_categories/fold2 --tasks instruments --metrics segmentation --filter --selection topk_thresh --selection_info 5,0.1

python evaluate.py --coco-ann-path /media/SSD1/scanar/endovis/LEMIS-challenge/region_proposals/data/sages_cutmargins/annotations/fold1/test_annotation_coco_polygon.json --pred-path /home/scanar/endovis/LEMIS-challenge/region_proposals/outputs/challenge/CVS_SwinL_cutted_from_end2023_cutted_fold1/inference/coco_instances_results.json --output_path ./metrics_outputs/Mask2Former/With_categories/fold1 --tasks instruments --metrics segmentation --filter --selection topk_thresh --selection_info 5,0.1
python evaluate.py --coco-ann-path /media/SSD1/scanar/endovis/LEMIS-challenge/region_proposals/data/sages_cutmargins/annotations/fold2/test_annotation_coco_polygon.json --pred-path /home/scanar/endovis/LEMIS-challenge/region_proposals/outputs/challenge/CVS_SwinL_cutted_from_end2023_cutted_fold2/inference/coco_instances_results.json --output_path ./metrics_outputs/Mask2Former/With_categories/fold2 --tasks instruments --metrics segmentation --filter --selection topk_thresh --selection_info 5,0.1