_BASE_: Base-CVS-InstanceSegmentation.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  WEIGHTS: "weights/model_final_swin_S.pkl"
  # Keeping the original COCO means and stds provided better transfer learning results than using Endovis 2017's
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 0.0001
  STEPS: (729, 1283)
  MAX_ITER: 1458
  CHECKPOINT_PERIOD: 15 
TEST:
  EVAL_PERIOD: 15
